#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';
$app = new Symfony\Component\Console\Application('AZE Installer', '1.0.0');
$app->add(new AZE\console\command\ServeCommand());
$app->run();